services:
  - type: web
    name: ml-afiliados-bot
    region: frankfurt
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: WHATSAPP_TARGET_NUMBER
        sync: false
      - key: WHATSAPP_TARGET_GROUP
        sync: false
      - key: ML_AFFILIATE_TAG
        sync: false
      - key: ML_SEARCH_KEYWORD
        value: "Xiaomi, iPhone, Samsung Galaxy, TV AOC, TV LG, TV Philco, fone de ouvido bluetooth, monitor gamer, projetor, drone camera, tablet, acessorios pc gamer, cabo hdmi hub usb, teclado mouse gamer"
      - key: CRON_CAPTURE_SCHEDULE
        value: "0 * * * *"
      - key: CRON_PUBLISH_SCHEDULE
        value: "*/5 * * * *"
