services:
  - type: web
    name: ml-afiliados-bot
    region: frankfurt
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: WHATSAPP_TARGET_NUMBER
        sync: false
      - key: WHATSAPP_TARGET_GROUP
        sync: false
      - key: ML_AFFILIATE_TAG
        sync: false
      - key: ML_SEARCH_KEYWORD
        value: "Panelas inox, Panelas antiaderente, Frigideira, Jogo de talheres, pratos gourmet, copos xícaras, Liquidificador, Air fryer, Micro-ondas, Escorredor de louça, Porta temperos, Potes herméticos, Tábua de corte, Garrafa térmica, Sanduicheira, Cafeteira, Vassoura, Rodo, Pá de lixo, Balde, Mop esfregão, Panos de microfibra, Máquina de lavar, cesto de roupa, Varal de chão, Varal de parede, Ferro de passar, Sofá retrátil, Rack sala, painel TV, Televisão, Tapete sala, Cortina, Ventilador, ar-condicionado, Cama box, colchão casal, Guarda-roupa casal, Travesseiros, Lençóis cama, Cobertores, Chuveiro elétrico, Caixa organizadora, Cestos multiuso, Organizador de gaveta, Prateleira, Nicho parede, Carrinho organizador"
      - key: CRON_CAPTURE_SCHEDULE
        value: "0 * * * *"
      - key: CRON_PUBLISH_SCHEDULE
        value: "*/5 * * * *"
